/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-transaction`; params?: Router.UnknownInputParams; } | { pathname: `/edit-transaction`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/manage-categories`; params?: Router.UnknownInputParams; } | { pathname: `/receipt-preview`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/laporan` | `/laporan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pengaturan` | `/pengaturan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/transaksi` | `/transaksi`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-transaction`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-transaction`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/manage-categories`; params?: Router.UnknownOutputParams; } | { pathname: `/receipt-preview`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/laporan` | `/laporan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pengaturan` | `/pengaturan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/transaksi` | `/transaksi`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-transaction${`?${string}` | `#${string}` | ''}` | `/edit-transaction${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/manage-categories${`?${string}` | `#${string}` | ''}` | `/receipt-preview${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/laporan${`?${string}` | `#${string}` | ''}` | `/laporan${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pengaturan${`?${string}` | `#${string}` | ''}` | `/pengaturan${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/transaksi${`?${string}` | `#${string}` | ''}` | `/transaksi${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-transaction`; params?: Router.UnknownInputParams; } | { pathname: `/edit-transaction`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/manage-categories`; params?: Router.UnknownInputParams; } | { pathname: `/receipt-preview`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/laporan` | `/laporan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pengaturan` | `/pengaturan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/transaksi` | `/transaksi`; params?: Router.UnknownInputParams; };
    }
  }
}
